### ISSUE TITLE
Pagination issue and JS issue in article

### ISSUE THREAD

**Issue by kasunam** [kyleledbetter/apptheme#1]
Hi Kyle,

Amazing work with the theme. :) Couple of issues that we encountered so far.
1. Pagination is not working properly with the back end template. When clicked on either "Next", "Previous" links or other links (numbers) of the pagination , page redirects to joomla admin landing page.
2. When adding an article, after clicked save,save and new,save and close button browser got stuck, and js busy notification appeared. See the screen bellow.

![image](https://f.cloud.github.com/assets/4569467/584460/2a39136e-c918-11e2-8ac5-f2be687cbf0c.png)

Appreciate it if you could have a look and let us know what's the issue with these. :+1: thanks :)

**Comment by kyleledbetter** [comment]
Hi,
Thanks for the kinds words :)
1. to fix the pagination copy /administrator/templates/isis/html/pagination.php over to /administrator/templates/apptheme-admin/html/pagination.php (overwrite the file)
2. I haven't seen that error, looks like a mootools/IE issue. Can you try another browser like Chrome or Firefox? Or possibly another editor like JCE and see if the issue remains

**Comment by kyleledbetter** [comment]
Fixed in latest version
