### ISSUE TITLE
Problem with joomla user extend plugin

### ISSUE THREAD

**Issue by amilabandara** [kyleledbetter/apptheme#3]
I created a user extend plugin for extend user profile. Usually new fields show in back end user profile. But in apptheme those fields aren't showing. I changed admin template to joomla default template then extended fields appear.

**Comment by kyleledbetter** [comment]
Hi, are you referring to the User Profile tab in this screenshot?
![apptheme-user-profile](https://f.cloud.github.com/assets/867883/849420/3b80ec82-f474-11e2-9ccc-0d1d6cb6e807.png)

**Comment by amilabandara** [comment]
Yes . But there is no User Profile tab in my apptheme template. I checked
in code level. All my profile fields come with $field array. But they
aren't displaying.
when I changed admin template to another one it works fine.

Thank you

On Wed, Jul 24, 2013 at 8:48 PM, Kyle Ledbetter notifications@github.comwrote:

> Hi, are you referring to the User Profile tab in this screenshot?
> [image: apptheme-user-profile]https://f.cloud.github.com/assets/867883/849420/3b80ec82-f474-11e2-9ccc-0d1d6cb6e807.png
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kyleledbetter/apptheme/issues/3#issuecomment-21492239
> .

## 

Best Regards,
*Amila Bandara
Software Engineer

Phone :(+94) 077 47 55 900
E mail : amila128@gmail.com

Skype  : amilaishere
Web    : www.amilaishere.com
*
-  ෴Open Mind Beats The Limit෴*

**Comment by kyleledbetter** [comment]
Please email a super user account support@pixelpraise.com so i can take a look

**Comment by kyleledbetter** [comment]
Hi,
The User Profile plugin wasn't enabled. I've enabled it and now it's showing when you edit a user

**Comment by amilabandara** [comment]
Thank you.

On Thu, Jul 25, 2013 at 9:20 PM, Kyle Ledbetter notifications@github.comwrote:

> Hi,
> The User Profile plugin wasn't enabled. I've enabled it and now it's
> showing when you edit a user
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kyleledbetter/apptheme/issues/3#issuecomment-21563643
> .

## 

Best Regards,
*Amila Bandara
Software Engineer

Phone :(+94) 077 47 55 900
E mail : amila128@gmail.com
             amila@amilaishere.com
Skype  : amilaishere
Web    : www.amilaishere.com
*
-  ෴Open Mind Beats The Limit෴*
